"use client";

import { useState, type MouseEvent } from "react";
import {
  CheckCircle2,
  Sparkles,
  Copy,
  Check,
  Download,
  RotateCcw,
} from "lucide-react";

import NextActions from "./NextActions";

type Props = {
  jobDescription: string;
  onGenerateAnother: () => void;
};

export default function JobDescriptionResult({
  jobDescription,
  onGenerateAnother,
}: Props) {
  const [copied, setCopied] = useState(false);

  if (!jobDescription) return null;

  async function handleCopy() {
    await navigator.clipboard.writeText(jobDescription);

    setCopied(true);

    setTimeout(() => {
      setCopied(false);
    }, 2000);
  }

  function handleDownloadPDF(
    event: MouseEvent<HTMLButtonElement>
  ): void {
    event.preventDefault();

    const escapedLines = jobDescription
      .split("\n")
      .map((line) =>
        line
          .replace(/\\/g, "\\\\")
          .replace(/\(/g, "\\(")
          .replace(/\)/g, "\\)")
      );

    const wrappedLines = escapedLines.flatMap((line) => {
      const maxCharsPerLine = 90;

      const words = line.split(" ");

      const lines: string[] = [];

      let currentLine = "";

      words.forEach((word) => {
        const nextLine = currentLine
          ? `${currentLine} ${word}`
          : word;

        if (
          nextLine.length > maxCharsPerLine &&
          currentLine
        ) {
          lines.push(currentLine);
          currentLine = word;
        } else {
          currentLine = nextLine;
        }
      });

      if (currentLine) lines.push(currentLine);

      if (lines.length === 0) lines.push("");

      return lines;
    });

    const content = `BT
/F1 12 Tf
50 742 Td
${wrappedLines
  .map((line) => `(${line}) Tj`)
  .join("\n0 -14 Td\n")}
ET
`;

    const pdfObjects = [
      `1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
`,
      `2 0 obj
<< /Type /Pages /Count 1 /Kids [3 0 R] /MediaBox [0 0 612 792] >>
endobj
`,
      `3 0 obj
<< /Type /Page /Parent 2 0 R /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>
endobj
`,
      `4 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>
endobj
`,
      `5 0 obj
<< /Length ${content.length} >>
stream
${content}endstream
endobj
`,
    ];

    let pdf = "%PDF-1.3\n";

    const offsets: number[] = [];

    let position = pdf.length;

    pdfObjects.forEach((object) => {
      offsets.push(position);
      pdf += object;
      position = pdf.length;
    });

    const xrefStart = position;

    pdf += `xref
0 ${pdfObjects.length + 1}
0000000000 65535 f 
`;

    offsets.forEach((offset) => {
      pdf += `${offset
        .toString()
        .padStart(10, "0")} 00000 n 
`;
    });

    pdf += `trailer
<< /Size ${pdfObjects.length + 1} /Root 1 0 R >>
startxref
${xrefStart}
%%EOF`;

    const blob = new Blob([pdf], {
      type: "application/pdf",
    });

    const link = document.createElement("a");

    link.href = URL.createObjectURL(blob);

    link.download = "job-description.pdf";

    link.click();

    URL.revokeObjectURL(link.href);
  }

  return (
    <div className="mt-10 animate-fade-up rounded-3xl border border-border bg-card p-8 shadow-soft">

      {/* Success */}

      <div className="mb-8 flex items-center gap-4 rounded-2xl bg-green-50 p-5">

        <CheckCircle2 className="h-8 w-8 text-green-600" />

        <div>
          <h2 className="text-xl font-bold text-green-700">
            Job Description Generated
          </h2>

          <p className="text-sm text-green-700">
            Your AI-powered job description is ready.
          </p>
        </div>

      </div>

      {/* AI Badge */}

      <div className="mb-6 inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">

        Generated by Growvelt Assistant

      </div>

      {/* Header */}

      <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">

        <div className="flex items-center gap-3">

          <h2 className="text-3xl font-bold">
            Job Description
          </h2>

        </div>

        <div className="flex flex-wrap gap-3">

          <button
            onClick={handleCopy}
            className="flex cursor-pointer items-center gap-2 rounded-xl border border-border px-4 py-2 transition hover:bg-accent"
          >
            {copied ? (
              <>
                <Check size={18} />
                Copied
              </>
            ) : (
              <>
                <Copy size={18} />
                Copy
              </>
            )}
          </button>

          <button
            onClick={handleDownloadPDF}
            className="flex cursor-pointer items-center gap-2 rounded-xl bg-primary px-4 py-2 text-white transition hover:opacity-90"
          >
            <Download size={18} />
            PDF
          </button>

          <button
            onClick={onGenerateAnother}
            className="flex cursor-pointer items-center gap-2 rounded-xl border border-border px-4 py-2 transition hover:bg-accent"
          >
            <RotateCcw size={18} />
            Generate Another
          </button>

        </div>

      </div>

      {/* Document */}

      <div className="mt-10 rounded-2xl border border-border bg-background p-8">

        <pre className="whitespace-pre-wrap font-sans leading-8 text-foreground">
          {jobDescription}
        </pre>

      </div>

      <NextActions />

    </div>
  );
}