"use client";

import { useState, MouseEvent } from "react";
import NextActions from "./NextActions";
import {
  CheckCircle2,
  Copy,
  Check,
  Download,
  Target,
  AlertCircle,
  Lightbulb,
} from "lucide-react";

type Analysis = {
  score: number;
  atsScore: number;
  strengths: string[];
  missingSkills: string[];
  recommendations: string[];
  summary: string;
};

type Props = {
  analysis: Analysis;
};

export default function CandidateScreeningResult({
  analysis,
}: Props) {
  const [copied, setCopied] = useState(false);

  if (!analysis) return null;

  const report = `
Overall Match Score: ${analysis.score}/100

ATS Compatibility: ${analysis.atsScore}/100

SUMMARY

${analysis.summary}

STRENGTHS

${analysis.strengths.map((s) => `• ${s}`).join("\n")}

MISSING SKILLS

${analysis.missingSkills.map((s) => `• ${s}`).join("\n")}

HIRING RECOMMENDATIONS

${analysis.recommendations.map((s) => `• ${s}`).join("\n")}
`;

  async function handleCopy() {
    await navigator.clipboard.writeText(report);

    setCopied(true);

    setTimeout(() => {
      setCopied(false);
    }, 2000);
  }

  function handleDownloadPDF(e: MouseEvent<HTMLButtonElement>) {
    e.preventDefault();

    const escapedLines = report
      .split("\n")
      .map((line) =>
        line
          .replace(/\\/g, "\\\\")
          .replace(/\(/g, "\\(")
          .replace(/\)/g, "\\)")
      );

    const wrappedLines = escapedLines.flatMap((line) => {
      const max = 90;
      const words = line.split(" ");

      const result: string[] = [];
      let current = "";

      words.forEach((word) => {
        const next = current ? `${current} ${word}` : word;

        if (next.length > max && current) {
          result.push(current);
          current = word;
        } else {
          current = next;
        }
      });

      if (current) result.push(current);

      return result.length ? result : [""];
    });

    const content = `BT
/F1 12 Tf
50 742 Td
${wrappedLines
  .map((line) => `(${line}) Tj`)
  .join("\n0 -14 Td\n")}
ET`;

    const objects = [
      `1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj`,
      `2 0 obj
<< /Type /Pages /Count 1 /Kids [3 0 R] /MediaBox [0 0 612 792] >>
endobj`,
      `3 0 obj
<< /Type /Page /Parent 2 0 R /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>
endobj`,
      `4 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>
endobj`,
      `5 0 obj
<< /Length ${content.length} >>
stream
${content}
endstream
endobj`,
    ];

    let pdf = "%PDF-1.3\n";
    const offsets: number[] = [];
    let pos = pdf.length;

    objects.forEach((o) => {
      offsets.push(pos);
      pdf += o;
      pos = pdf.length;
    });

    const start = pos;

    pdf += `xref
0 ${objects.length + 1}
0000000000 65535 f 
`;

    offsets.forEach((o) => {
      pdf += `${o.toString().padStart(10, "0")} 00000 n 
`;
    });

    pdf += `trailer
<< /Size ${objects.length + 1} /Root 1 0 R >>
startxref
${start}
%%EOF`;

    const blob = new Blob([pdf], {
      type: "application/pdf",
    });

    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = "candidate-screening-report.pdf";
    link.click();

    URL.revokeObjectURL(link.href);
  }

  return (
    <div className="mt-10 rounded-3xl border border-gray-200 bg-white p-8 shadow-lg">

      <div className="mb-8 flex items-center gap-3 rounded-2xl bg-green-50 p-5">

        <CheckCircle2 className="h-8 w-8 text-green-600" />

        <div>
          <h2 className="text-xl font-bold text-green-700">
            Candidate Analysis Complete
          </h2>

          <p className="text-sm text-green-700">
            Growvelt Assistant has finished evaluating this candidate.
          </p>
        </div>

      </div>

      <div className="mb-6 inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">
        Generated by Growvelt Assistant
      </div>

      <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">

        <div className="flex items-center gap-3">

          <h2 className="text-3xl font-bold">
            Candidate Screening Report
          </h2>
        </div>

        <div className="flex flex-wrap gap-3">

          <button
            onClick={handleCopy}
            className="flex items-center gap-2 rounded-xl border px-4 py-2 hover:bg-gray-100"
          >
            {copied ? (
              <>
                <Check size={18} />
                Copied
              </>
            ) : (
              <>
                <Copy size={18} />
                Copy
              </>
            )}
          </button>

          <button
            onClick={handleDownloadPDF}
            className="flex items-center gap-2 rounded-xl bg-purple-600 px-4 py-2 text-white hover:bg-purple-700"
          >
            <Download size={18} />
            PDF
          </button>

        </div>

      </div>

      <div className="mt-10 grid gap-6 md:grid-cols-2">

        <ScoreCard
          title="Overall Match Score"
          score={analysis.score}
        />

        <ScoreCard
          title="ATS Compatibility"
          score={analysis.atsScore}
        />

      </div>

      <Section
        icon={<CheckCircle2 className="h-5 w-5 text-green-600" />}
        title="Summary"
        items={[analysis.summary]}
      />

      <Section
        icon={<CheckCircle2 className="h-5 w-5 text-green-600" />}
        title="Strengths"
        items={analysis.strengths}
      />

      <Section
        icon={<AlertCircle className="h-5 w-5 text-orange-500" />}
        title="Missing Skills"
        items={analysis.missingSkills}
      />

      <Section
        icon={<Lightbulb className="h-5 w-5 text-purple-600" />}
        title="Hiring Recommendations"
        items={analysis.recommendations}
      />

<NextActions />

    </div>
  );
}

function ScoreCard({
  title,
  score,
}: {
  title: string;
  score: number;
}) {
  return (
    <div className="rounded-2xl border bg-gray-50 p-6">
      <div className="flex items-center gap-2">
        <Target className="text-primary" />
        <span className="font-semibold">{title}</span>
      </div>

      <div className="mt-4 text-5xl font-black text-primary">
        {score}%
      </div>
    </div>
  );
}

function Section({
  icon,
  title,
  items,
}: {
  icon: React.ReactNode;
  title: string;
  items: string[];
}) {
  return (
    <div className="mt-6 rounded-2xl border bg-gray-50 p-6">

      <div className="mb-4 flex items-center gap-2">
        {icon}
        <h3 className="text-xl font-bold">{title}</h3>
      </div>

      <ul className="space-y-3">
        {items.map((item, index) => (
          <li
            key={index}
            className="rounded-xl bg-white p-3"
          >
            {item}
          </li>
        ))}
      </ul>

      

    </div>
    
  );
}